In [52]:
import pandas as pd
import seaborn as sns
sns.set_theme()

In [53]:
df = pd.read_excel('/Users/ammar-imac/Downloads/A+ Party.xlsx')
df.sort_values('Start time', inplace=True, ascending=False)
df.drop_duplicates('KFUPM ID', inplace=True)
df

,ID,Start time,Completion time,Email,Name,KFUPM ID,Full name,Do you confirm your attendance in the specified Date and Time above ?,Are you excited ?
423,424,2023-01-31 10:44:14,2023-01-31 10:44:38,anonymous,NaN,201953230,Hamoud Alghizzi,Yes,Yes
422,423,2023-01-31 09:57:43,2023-01-31 09:58:42,anonymous,NaN,202030240,Ali Hussain Alyaseen,Yes,Yes
421,422,2023-01-31 09:04:32,2023-01-31 09:04:52,anonymous,NaN,202252120,Mohammed Rashad Mudhsh Ali,Yes,Yes
420,421,2023-01-31 07:23:05,2023-01-31 07:23:35,anonymous,NaN,202156130,Hassan Habeeb Almaqdoud,Yes,Yes
419,420,2023-01-31 05:44:20,2023-01-31 05:44:48,anonymous,NaN,202160590,Ahmed Jamal Al-Omran,Yes,Yes
...,...,...,...,...,...,...,...,...,...
13,14,2023-01-29 09:17:27,2023-01-29 09:18:22,anonymous,NaN,202043860,Mohamad Ghazi Shabareq,Yes,Yes
10,11,2023-01-29 09:17:27,2023-01-29 09:18:16,anonymous,NaN,202169110,Nada Anwar Alkhawajah,Yes,Yes
21,22,2023-01-29 09:17:26,2023-01-29 09:18:41,anonymous,NaN,201970030,Mohammed Abdullah Almashhaf,Yes,Yes
15,16,2023-01-29 09:17:24,2023-01-29 09:18:23,anonymous,NaN,202133050,Abdullah Omar Almulhim,Yes,Yes
0,1,2023-01-29 09:17:13,2023-01-29 09:17:40,anonymous,NaN,202259660,Faysal Mohammed Alqahtani,Yes,Yes

In [54]:
df['Do you confirm your attendance in the specified Date and Time above ?'].value_counts()

Yes    253
No       4
Name: Do you confirm your attendance in the specified Date and Time above ?, dtype: int64

In [46]:
df['Do you confirm your attendance in the specified Date and Time above ?'].describe()

count     247
unique      2
top       Yes
freq      243
Name: Do you confirm your attendance in the specified Date and Time above ?, dtype: object