In [39]:
import pandas as pd
import seaborn as sns
sns.set_theme()

In [43]:
df = pd.read_excel('/Users/ammar-imac/Downloads/A+ Party.xlsx')
df.sort_values(['Start time', 'KFUPM ID'], inplace=True, ascending=False)
df.drop_duplicates('KFUPM ID', inplace=True)
df

,ID,Start time,Completion time,Email,Name,KFUPM ID,Full name,Do you confirm your attendance in the specified Date and Time above ?,Are you excited ?
397,398,2023-01-30 18:35:32,2023-01-30 18:36:23,anonymous,NaN,202042340,HUSAM NOORWALI,Yes,Yes
396,397,2023-01-30 18:16:27,2023-01-30 18:16:42,anonymous,NaN,202173730,Hamza Ibrahim Alshaikhi,Yes,No
395,396,2023-01-30 18:01:48,2023-01-30 18:02:12,anonymous,NaN,202020460,Hayder Mohammed Aleissa,No,No
394,395,2023-01-30 17:59:09,2023-01-30 17:59:45,anonymous,NaN,202034060,Ahmed Salem Alharbi,Yes,Yes
393,394,2023-01-30 17:54:33,2023-01-30 17:54:49,anonymous,NaN,202011940,Abdulrahman Alothman,Yes,Yes
...,...,...,...,...,...,...,...,...,...
10,11,2023-01-29 09:17:27,2023-01-29 09:18:16,anonymous,NaN,202169110,Nada Anwar Alkhawajah,Yes,Yes
13,14,2023-01-29 09:17:27,2023-01-29 09:18:22,anonymous,NaN,202043860,Mohamad Ghazi Shabareq,Yes,Yes
21,22,2023-01-29 09:17:26,2023-01-29 09:18:41,anonymous,NaN,201970030,Mohammed Abdullah Almashhaf,Yes,Yes
15,16,2023-01-29 09:17:24,2023-01-29 09:18:23,anonymous,NaN,202133050,Abdullah Omar Almulhim,Yes,Yes
0,1,2023-01-29 09:17:13,2023-01-29 09:17:40,anonymous,NaN,202259660,Faysal Mohammed Alqahtani,Yes,Yes

In [35]:
df['Do you confirm your attendance in the specified Date and Time above ?'].value_counts()

Yes    243
No       4
Name: Do you confirm your attendance in the specified Date and Time above ?, dtype: int64

In [46]:
df['Do you confirm your attendance in the specified Date and Time above ?'].describe()

count     247
unique      2
top       Yes
freq      243
Name: Do you confirm your attendance in the specified Date and Time above ?, dtype: object